tooltips = new Array;
tooltips['ratf'] = "属性：增加10点的攻击力。提高5点/秒的生命回复速度。提高125%的魔法回复速度。";
tooltips['klmm'] = "属性：增加2点的所有属性。<br><br><span style=\"color:#99ccff\">回复光环(被动)<br>效果：(+3 点/秒的生命回复速度) (500 有效范围)。</span>";
tooltips['sfog'] = "属性：增加5点的护甲。增加2点的所有属性。<br><br><span style=\"color:#99ccff\">防御提升（主动）<br>激活后 (消耗50点的魔法，冷却时间15秒): 提升周围友方单位2点的护甲 (700 有效范围) ，持续15(30对非英雄单位)秒。</span>";
tooltips['I01J'] = "属性：增加6点的攻击力。<br><br><span style=\"color:#99ccff\">专注光环（被动）<br>专注光环 (+3 点的护甲) (900 有效范围).<br>辉煌光环（被动）<br>辉煌光环 (+0.65/秒 的魔法回复速度) (900 有效范围).<br>可拆分</span>";
tooltips['tlum'] = "属性：提升95的移动速度。<br><br><span style=\"color:#99ccff\">传送（主动）<br>激活后 (消耗75点的魔法，冷却时间60秒): 传送 至友方的一个建筑或非英雄单位 (施法时间3秒)。</span><br><br><span style=\"color:#ff0303\">提升效果不能和速度之靴、动力鞋、或者其它远行鞋叠加。</span><br /><br />详解请访问http://DotA.<b style=\"color:red;\">R</b>eplays.<b style=\"color:red;\">N</b>et论坛DotA综合区.";
tooltips['I01V'] = "属性：提升60的移动速度,增加25%的攻击速度,增加10点任意属性(可切换)。 <br><br><span style=\"color:#ff0303\">提升效果不能和速度之靴，远行鞋或者其他动力鞋叠加。<br>装备唯一</span>";
tooltips['pdiv'] = "属性：提升30%的攻击速度。<br><br><span style=\"color:#99ccff\">炼制（主动）<br>激活后 (消耗25点的魔法，冷却时间100秒): 炼制 (最高可将6级非远古野怪转化为金钱，施法距离 600)。</span>";
tooltips['soul'] = "属性：增加6点的智力。增加15点的攻击力。提高75%的魔法回复速度。提升10%的攻击速度。";
tooltips['tfar'] = "属性：增加3点的属性。额外增加3点的力量。";
tooltips['sor9'] = "属性：增加3点的属性。额外增加3点的敏捷。";
tooltips['gsou'] = "属性：增加3点的属性。额外增加3点的智力。";
tooltips['rde0'] = "属性：增加16点的敏捷。提升15%的攻击速度。提升10%的移动速度。";
tooltips['ram1'] = "属性：增加10点的攻击力。增加16点的力量。<br><br><span style=\"color:#99ccff\">残废（被动）在攻击中有15%的概率使目标残废.<br>残废效果: 降低目标20% 的移动速度，持续4秒。</span>";
tooltips['nspi'] = "属性：增加40点的攻击力。增加3点的力量。<br><br><span style=\"color:#99ccff\">重击（被动）<br>重击 (近身攻击有25% 的几率造成1.4秒的眩晕，远程攻击有10% 的几率造成1.4秒的眩晕，2秒不与任何被动击晕技能叠加)。</span>";
tooltips['rat6'] = "属性：增加5点的护甲。增加22点的攻击力。增加10点智力。<br><br><span style=\"color:#99ccff\">尖刺（主动）<br>激活后(消耗25点的魔法，冷却时间22秒): 将所受伤害100%反弹给攻击者(反弹属于神圣伤害，刃甲不再反弹来源为刃甲的伤害)。持续4秒。</span>";
tooltips['rots'] = "属性：增加20点的攻击力，5点的护甲。增加15%的吸血。<br><br><span style=\"color:#99ccff\">支配（主动）<br>激活后 (消耗200点的魔法，冷却时间300秒): 蛊惑 (长时间控制一个非英雄单位，并能获得英雄单位的魔法抗性.最高级别 6，施法距离 700)。</span><br /><br />详解请访问http://DotA.<b style=\"color:red;\">R</b>eplays.<b style=\"color:red;\">N</b>et论坛DotA综合区.";
tooltips['horl'] = "属性：增加17%的吸血。<br><br><span style=\"color:#99ccff\">狂热（主动）<br>激活后 (消耗25点的魔法，冷却时间25秒): 12 秒的狂热 (+100% 的攻击速度，+20% 的移动速度，+30% 所受伤害将即时计算)。</span>";
tooltips['rej2'] = "属性：增加10点的智力。提升125%的魔法回复速度。提升25的移动速度。<br><br><span style=\"color:#99ccff\">龙卷风（主动）<br>激活后 (无限使用，冷却时间30秒): 龙卷风 (造成对方停留在空中2.5 秒) (施法距离 700)。可对自己使用。</span>";
tooltips['oslo'] = "属性：增加500点的生命。增加400点的魔法。提高100%的魔法回复速度和4点/秒的生命回复速度。";
tooltips['mnst'] = "属性：增加5点的所有属性。增加5点的护甲。<br><br><span style=\"color:#99ccff\">回复光环（被动）<br>效果：(+4 点/秒的生命回复速度) (500 有效范围)。<br><br>活力（主动）<br>激活后 (消耗150 点的魔法，冷却时间45 秒): 周围友方单位恢复250点的生命，+2 点的护甲 持续时间20秒 (750 有效范围)。</span>";
tooltips['rnsp'] = "属性：增加12点的攻击力。增加16点的力量。增加16点的敏捷。提升12%的移动速度。提升15%的攻击速度。<br><br><span style=\"color:#99ccff\">残废（被动）攻击有15%的概率使目标残废.<br>法球效果:降低30%的移动速度和15%的攻击速度,持续4秒。</span>";
tooltips['tels'] = "属性：增加60点的攻击力。<br><br><span style=\"color:#99ccff\">腐蚀攻击（被动）<br>法球效果: 降低对方6点的护甲，持续时间5秒。</span>";
tooltips['gldo'] = "属性：增加65点的攻击力。提高150%的魔法回复速度、6点/秒的生命回复速度。<br><br><span style=\"color:#99ccff\">溅射攻击（被动）<br>效果: 溅射攻击 (35%的伤害，200 有效范围，仅近身单位使用时有效)。</span>";
tooltips['lure'] = "属性：增加35点的攻击力。<br><br><span style=\"color:#99ccff\">致命一击（被动）<br>效果: 致命一击 (15% 的几率, 1.75倍伤害)。</span>";
tooltips['ofro'] = "属性：增加10点的力量。增加24点的攻击力。<br><br><span style=\"color:#99ccff\">天神下凡（主动）<br>激活后（不消耗魔法），10/9/8/7/6/5秒的天神下凡（对魔法免疫），80/75/70/65/60/55秒冷却时间。</span>";
tooltips['ccmd'] = "属性：增加38点的攻击力。增加10%攻速。 <br><br><span style=\"color:#99ccff\">疾风步（主动）<br>激活后 (消耗50点的魔法，冷却时间18 秒): 使用者进入疾风步状态，期间增加其20%的移动和速度，持续9秒，显身一击附加125点伤害。</span>";
tooltips['rej1'] = "属性：增加3点的所有属性。增加12点的智力。增加9点的攻击力。<br><br><span style=\"color:#99ccff\">能量冲击（主动）<br>+3所有属性，+9攻击，+12/14/16/18/20智力激活后 (消耗180/160/140/120/100 点的魔法，冷却时间40/36/32/28/24秒): 400/500/600/700/800 点的 能量冲击 (施法距离 600/650/700/750/800)。 可以通过购买卷轴升级; 最多能升级4次。</span>";
tooltips['I001'] = "属性：增加15点的智力。增加6点的力量。<br><br><span style=\"color:#99ccff\">召唤死灵（主动）<br>+8/12/16 点的力量，+15/21/24 点的智力,激活后 (消耗50 点的魔法，冷却时间90 秒): 复活死灵, 召唤拥有特殊能力的 1 个恶魔战士 (400/600/800 的生命值，21/41/61 的普通攻击力，6/8/10 点的护甲，40%的魔法伤害减免，25/50/75 点/攻击的法力损毁 (同时减少60% 魔法损毁的生命值) ，对杀死它的单位造成200/400/600 点伤害的最后遗愿，第三级时拥有魔法岗哨 (视野 1000，具有真视能力) )   和 1 个恶魔射手 (400/600/800 的生命值，31/61/91 的穿刺攻击力，350/450/550 的攻击射程，6/8/10 点的护甲，40%的魔法伤害减免，+3%/6%/9% 攻击和移动速度的耐久光环 (400 有效范围) ，200/250/300 点的法力燃烧 (同时造成等量伤害，施法距离 250) ) 为你战斗(同一时间每人只能召唤一组，<span style=\"color:#ff0000\">可以</span>攻击远古单位，被敌击杀后各掉落100金币)，持续时间35 秒。可以通过购买卷轴升级; 最多能升2次。</span>";
tooltips['pspd'] = "属性：增加250点的攻击力。";
tooltips['ofir'] = "属性：增加81点的攻击力。<br><br><span style=\"color:#99ccff\">致命一击（被动）<br>效果: 致命一击 (20% 的几率, 2.4倍伤害)。</span>";
tooltips['ram4'] = "属性：增加60点的攻击力。<br><br><span style=\"color:#99ccff\">辉耀（被动）<br>效果: 献祭 (在650范围内造成40 点伤害/秒，对远古单位无效果)。</span>";
tooltips['kgal'] = "属性：增加40点的力量，300点的生命。提高2%/秒的被动生命值回复.<br><span style=\"color:red\">只能在战场之外为您提供恢复能力（6秒内不能受到来自敌方英雄的攻击）<br />不可叠加。</span>";
tooltips['bfhr'] = "属性：增加25%的吸血。增加25点的力量，5点的护甲。<br><br><span style=\"color:#99ccff\">不洁狂热（主动）<br>激活后 (持续3.5秒，冷却时间35秒): +30点攻击力，额外增加175%吸血。</span>";
tooltips['thdm'] = "属性：增加25点的所有属性。增加200点的生命。增加150点的魔法。<br><br><span style=\"color:#99ccff\">霜冻攻击（被动）<br>法球效果: 霜冻攻击 (-20% 的攻击速度，-30% 的移动速度 持续2秒)。</span>";
tooltips['rde4'] = "属性：增加30点的敏捷。增加30点的攻击力。提升30%的攻击速度。30%的闪避。";
tooltips['oven'] = "属性：提高5点/秒的生命回复速度。提高200%的魔法回复速度。增加40点的攻击力。 <br><br><span style=\"color:#99ccff\">刷新（主动）<br>激活后 (消耗375 点的魔法，冷却时间210 秒): 立刻 结束所有物品/技能的冷却进程 (不包括刷新球本身)。</span>";
tooltips['spre'] = "属性：增加35点的智力。增加10点的力量。增加10点的敏捷。提高200%的魔法回复速度。<br><br><span style=\"color:#99ccff\">妖术（主动）<br>激活后(消耗100点魔法、冷却时间35秒)将目标变成一只绵羊，期间只能保留部分被动技能效果且不能攻击、只有缓慢的移动速度，持续3.5秒。</span>";
tooltips['I00L'] = "属性：增加275点的生命。提高6点/秒的生命回复速度。受到普通攻击时有70%的几率抵挡40点的伤害（远程先锋盾：70%抵挡20点伤害）。";
tooltips['I00T'] = "属性：增加4点的护甲。增加300点的魔法值。<br><br><span style=\"color:#99ccff\">恢复魔法（主动）<br>激活后 (消耗25 点的魔法，冷却时间33 秒): 恢复600范围内友方单位135点魔法。</span><br /><br />详解请访问http://DotA.<b style=\"color:red;\">R</b>eplays.<b style=\"color:red;\">N</b>et论坛DotA综合区.";
tooltips['I00Q'] = "属性：增加20点的攻击力,增加70点攻击速度。<br><br><span style=\"color:#99ccff\">连环闪电（被动）<br>法球效果:攻击中有20%几率释放出跳跃4次,160点伤害的连环闪电,不衰减<br>静电冲击（主动）<br>效果:受到攻击时有20%几率对攻击者及附近最多3个单位释放200点伤害的叉状闪电  持续时间:20秒 冷却时间:35秒</span>";
tooltips['I00W'] = "属性：非常好用的飞行运输单位。";
tooltips['I012'] = "属性：攻击光环（被动）吸血光环（被动）辉煌光环（被动）专注光环（被动）<br><span style=\"color:#99ccff\">效果：(900有效范围) +5点护甲，+0.8魔法每秒，+15%的攻击力，+16%吸血(仅近战攻击有效)。</span>";
tooltips['I01K'] = "属性：增加10点的护甲。提升35%的攻击速度。专注光环（被动）荒芜光环（被动）狂热光环（被动）<br><span style=\"color:#99ccff\">效果：(+5 点友方单位护甲，对建筑有效) (900 有效范围)。<br>效果：(-5 点非友方单位护甲，对建筑有效) (900有效范围)。<br>效果：(+20% 友方单位攻击速度) (900 有效范围)。</span><br /><br />详解请访问http://DotA.<b style=\"color:red;\">R</b>eplays.<b style=\"color:red;\">N</b>et论坛DotA综合区.";
tooltips['I01E'] = "属性：增加450点的生命增加400点的魔法提高200%的魔法回复速度提高8点/秒的生命回复速度。<br><br><span style=\"color:#99ccff\">血焰灌输(被动)：1000范围内有敌方英雄死亡时获得1点能量，死亡后失去1/3的能量，每点能量+1点/秒的魔法恢复速度，且充能可为神圣救赎提供更强大的效果（充能恢复效果不与按照百分比的魔法恢复速度挂钩）<br>救赎（被动）<br>有能量时死亡：1700范围内的友方单位将恢复450+(30*血精石能量点)的生命值，自己死亡时金钱损失减少(25*血精石能量点)，复活时间减少(3*血精石能量点),得到死亡前所处范围内的经验。</span>";
tooltips['I01F'] = "属性：提高30%的魔法抗性。提高8点/秒的生命回复速度。";
tooltips['I01Y'] = "属性：增加9点的攻击力。增加5点的护甲。提升15%的攻击速度。提高3点/秒的生命回复速度。<br><br><span style=\"color:#99ccff\">邪恶之力（主动）<br>冷却时间5秒，激活后属性变为：+40攻击，+25%攻击速度，+5点护甲，-35生命/秒的恢复速度，力量+25（生命上限+475） 。</span>";
tooltips['I01U'] = "属性：增加30点的智力。增加15点的护甲。<br><br><span style=\"color:#99ccff\">霜冷光环（被动）<br>1000范围内 减25%的攻击速度.<br>极寒冲击（主动）<br>激活后(魔法消耗：100点，冷却时间30秒)范围内非友军单位受到200伤害并减少40%的移动速度，持续4秒。</span>";
tooltips['I00C'] = "属性：增加20点的智力。增加45点的攻击力。提高30%的攻击速度。提高225%的魔法回复速度。<br><br><span style=\"color:#99ccff\">灵魂燃烧（主动）<br>激活后(消耗100点魔法、冷却时间18秒)沉默目标，并额外受到20%的伤害，持续5秒</span>";
tooltips['stre'] = "这双神奇的手套，似乎可以使武器变轻。提升15%的攻击速度。";
tooltips['jdrn'] = "再没比这个更拉风的了，增加15%的吸血。<br><br><span style=\"color:#99ccff\">法球效果 </span>";
tooltips['tkno'] = "这个戒指，在侏儒们的眼里是个幸运符，因为它能提高2点/秒的生命回复速度。 ";
tooltips['desc'] = "传说中艾泽拉斯大陆上来去如风的刺客科勒所使用的匕首。瞬间移动：最大距离1200，只有在3秒内没有受到英雄伤害时才能使用。魔法消耗：75点,冷却时间：14秒<br><br><span style=\"color:#ff0303\">复仇之魂（Shandelzare）和屠夫（Pudge）不能使用此物品。 </span>";
tooltips['shhn'] = "法师和术士们用来举办各种仪式的常用面具。提高50%的魔法回复速度。 .";
tooltips['tgxp'] = "普通跑鞋，提升50的移动速度。<br><br><span style=\"color:#ff0303\">提升效果不能和远行鞋、动力鞋、或者其它速度之靴叠加。 </span>";
tooltips['oflg'] = "这块水晶带给英雄真视能力。有6分钟进货时间<br><br><span style=\"color:#ff0303\">英雄死亡后掉落<br>不能出售 </span>";
tooltips['gvsm'] = "一个包含着生命本质的神秘球体。增加10点的所有属性。 ";
tooltips['sor1'] = "以魔法材质制作的斗篷可以抵御法术攻击，提高15%的魔法抗性。 ";
tooltips['plcl'] = "每瓶药水中都困着一个鲜活的小精灵。在30秒内恢复使用者100点的魔法值，受到攻击即失去效果。 ";
tooltips['sor8'] = "纯净深蓝的药水，在10秒内恢复一个友方单位400点的生命，受到攻击即失去效果。 ";
tooltips['silk'] = "肉食者转变成素食者时所创的物品。允许使用者吞食树木，在25秒内回复175点的生命。可使用3次。";
tooltips['I019'] = "年代久远的魔瓶，或者储存基地的生命泉水供3次使用，每次使用，在3秒内恢复单位135点的生命和70点的魔法；又或者储存一个神符供必要时使用，最多储存120秒，使用神符后魔瓶会回至满。";
tooltips['sor7'] = "消耗5点魔法放置一个侦察守卫来监视一定的区域，不具有真视能力。持续6分钟。可使用3次。";
tooltips['tgrh'] = "放置一个岗哨守卫来监视一定的区域，持续360秒，具有真视能力。可使用2次。真视范围：950";
tooltips['stwp'] = "将你传送至友方建筑，目标建筑在传送期间无敌。传送：将你传送至任意友方建筑。施法时间：3秒魔法消耗：75点冷却时间：65秒<br /><br /><span style=\"color:#ff0000\"> 双击回城卷轴会自动将你传送至泉水区域.</span>";
tooltips['sman'] = "制造一个小巧而快速的单位，帮助携带物品。如果它死了，它所携带的物品会掉落。 ";
tooltips['srtl'] = "恶魔军团的堕落统领所使用的武器，充满着邪恶的力量。增加46点的攻击力。";
tooltips['srbd'] = "用这把轻巧的弓进行攻击是如此的精准，就好像它自己会瞄准目标一样。增加25点的敏捷。 ";
tooltips['rump'] = "这把巨斧能够劈开一整条山脉。增加25点的力量。 ";
tooltips['shrs'] = "自远古就存在的强大的武器。你很难说清圣者遗物到底是什么，一般认为这是一柄剑。增加60点的攻击力，kao... ";
tooltips['sprn'] = "一块刻有神秘纹路的石头，能够提高携带者的激情。提升55%的攻击速度。 ";
tooltips['rej6'] = "在一个半身人肥仔的尸体上找到的闪闪发光的戒指。提高5点/秒的生命回复速度。  ";
tooltips['shcw'] = "这块宝石看起来蕴藏着无穷的能量。提高100%的魔法回复速度。 ";
tooltips['ram2'] = "这根谜一般的法杖是由最贵重的水晶做成的。增加25点的智力。 ";
tooltips['pgin'] = "这件精致的艺术品据说是由纯粹的能量构成的，增加250点的魔法。 ";
tooltips['hbth'] = "这颗神秘的宝石能够全面发掘英雄的潜能。增加150点魔法和200点生命。 ";
tooltips['oli2'] = "据说，它能带给神选之人（The Chosen Ones，呵呵）以不朽。至于别人嘛，它增加250点的生命。 ";
tooltips['stwa'] = "指节铜套--豪华版！增加3点的力量。";
tooltips['shdt'] = "用蜘蛛皮做的皮靴，能使你感到些许刺痛。增加3点的敏捷。  ";
tooltips['sbok'] = "穿上去像花花公子的蓝色斗篷；这个季节非常流行。增加3点的智力。";
tooltips['iwbr'] = "带上它们会确保一场好局(Good Game)。增加1点所有属性。";
tooltips['bgst'] = "这条巨大的腰带是在法师战争中，从倒下的泰坦身上剥下的，能提高携带者6点的力量。 ";
tooltips['belv'] = "增加6点的敏捷。";
tooltips['ciri'] = "这件长袍会腐蚀使用者的灵魂，但作为回报，会提高6点的智力。 ";
tooltips['tbar'] = "为人类公主们所设计的雅致头环。增加2点的所有属性。 ";
tooltips['sksh'] = "只是握着它就感觉自己变得更加强壮。增加10点力量。 ";
tooltips['tmmt'] = "充盈着时光魔法的长剑，增加10点的敏捷。 ";
tooltips['shtm'] = "一位堕落法师曾使用过的强力法杖，增加10点的智力。 ";
tooltips['tmsc'] = "虐待狂们的可选武器之一。增加9点的攻击力。";
tooltips['sor2'] = "想做个称职的骑士的话，就该买上一把。增加18点的攻击力。";
tooltips['whwd'] = "要4根短棍才能组成一根普通的棍子，kao！增加10点的攻击力，提升10%的攻击速度。 ";
tooltips['sora'] = "一把宝剑，既能够用来砍护甲，也可以用来切土豆。增加21点的攻击力。";
tooltips['modt'] = "也许是它尺寸太小的缘故，大多数人想戴上它的话会有点困难。增加2点的护甲。";
tooltips['I00Z'] = "与其说是标枪，倒更加像标准的长矛。用来攻击的时候能够穿透敌人的铠甲。增加21点的攻击力，攻击中有20%的几率造成40点的额外伤害。";
tooltips['flag'] = "由纯粹的密银打造而成的锤子，It's Hammer Time！增加24点攻击力。 ";
tooltips['tbsm'] = "金属锁链制成的编织甲，增加5点的护甲。边路商店可以购买 ";
tooltips['scul'] = "一位战死沙场的传奇般的武士使用过的头盔。增加5点的护甲并且提高3点/秒的生命回复速度。 ";
tooltips['ram3'] = "厚实的板甲能保护整个身体，增加10点的护甲。";
tooltips['v551'] = "增加己方所有建筑9999点护甲，持续4秒，冷却时间5分钟。";
tooltips['v552'] = "增加70点速度，24点攻击.<br><br><span style=\"color:#99ccff\">相位（主动）<br>增加16%的移动速度，碰撞体积为0（可以穿人，但不能无视地形），攻击或使用技能后buff消失。</span><br /><br /><span style=\"color:#99CCFF\">冷却时间：</span>10秒<br /><span style=\"color:#99CCFF\">持续时间：</span>5秒<br /><br />详解请访问http://DotA.<b style=\"color:red;\">R</b>eplays.<b style=\"color:red;\">N</b>et论坛DotA综合区.";
tooltips['v553'] = "真视范围1050，持续12秒，冷却时间60秒，可使用2次。显影效果不叠加，不具有开视野功能，只对英雄有效。";
tooltips['rosh'] = "重生(被动)英雄死亡后将在3秒后原地复活.<br><br><span style=\"color:red\">得到十分钟后如果未被使用将被回收.</span>";
tooltips['chee'] = "杀死3级的Roshan获得,瞬间恢复2500点生命1000点魔法.<br><br>将物品扔在商店中可卖出价值500";
tooltips['magi'] = "<span style=\"color:#FF8000\">充能（主动）：</span><br>使用后为你补充生命和魔法（补充效果取决于能量点数，每个能量点补充15点生命与魔法）；附近1500范围有敌方英雄单位施展技能时会自动充能（上限10次）<br /><br /><span style=\"color:#99CCFF\">冷却时间：</span>17秒";
tooltips['tali'] = "<span style=\"color:#FFCC00\">属性：</span><br />提升25%的闪避.";
tooltips['ghos'] = "<span style=\"color:#FFCC00\">属性：</span><br />增加7点所有属性.<br /><br /><span style=\"color:#FF8000\">幽魂形态（主动）：</span>你将进入灵魂形态4秒 会受到44%的额外魔法伤害,但是对物理攻击免疫.<br /><br /><span style=\"color:#99CCFF\">冷却时间：</span>25秒.<br /><span style=\"color:#99CCFF\">持续时间：</span>4秒.<br /><span style=\"color:#99CCFF\">消耗魔法：</span>75点.<br /><br />详解请访问http://DotA.<b style=\"color:red;\">R</b>eplays.<b style=\"color:red;\">N</b>et论坛DotA综合区.";
tooltips['6001'] = "<span style=\"color:#FFCC00\">属性：</span><br />提升10点每秒的生命回复速度<br />增加30%的魔抗性<br><br><span style=\"color:#FF8000\">魔法屏障（主动）：</span><br>神奇的人造品 能召唤能量立场保护附近的友军使他们可以抵挡400点法术伤害。<br /><span style=\"color:red\">50秒内不能叠加!</span><br /><br /><span style=\"color:#99CCFF\">冷却时间：</span>60秒.<br /><span style=\"color:#99CCFF\">持续时间：</span>8秒.<br /><span style=\"color:#99CCFF\">作用范围：</span>700.";
tooltips['forc'] = "<span style=\"color:#FFCC00\">属性：</span><br />增加10点攻击力<br />增加10点智力<br />提升10%的攻击速度<br><br><span style=\"color:#FF8000\">弹射（主动）：</span><br>将一个单位向其面对的方向推进600距离。<br /><br /><span style=\"color:#99CCFF\">施法距离：</span>800.<br /><span style=\"color:#99CCFF\">冷却时间：</span>20秒.<br /><span style=\"color:#99CCFF\">消耗魔法：</span>25点.<br /><br /><span style=\"color:#ff0000\">双击弹射法杖相当于对自己使用弹射.</span><br /><br />详解请访问http://DotA.<b style=\"color:red;\">R</b>eplays.<b style=\"color:red;\">N</b>et论坛DotA综合区.";
tooltips['v554'] = "<span style=\"color:#FFCC00\">属性：</span><br />增加3点所有属性<br /><br /><span style=\"color:#FF8000\">充能（主动）：</span><br>使用后为你补充生命和魔法（补充效果取决于能量点数，每个能量点补充15点生命与魔法）；附近1500范围有敌方英雄单位施展技能时会自动充能（上限15次）<br /><br /><span style=\"color:#99CCFF\">冷却时间：</span>17秒<br /><br />详解请访问http://DotA.<b style=\"color:red;\">R</b>eplays.<b style=\"color:red;\">N</b>et论坛DotA综合区.";
tooltips['rugt'] = "<span style=\"color:#FFCC00\">属性：</span><br />增加80点的攻击力<br />提升15%的攻击速度。<br><br><span style=\"color:#FF8000\">精确打击（被动）</span><br>攻击不会落空（该技能与其它一些技能有冲突，点击可以切换开关状态） 。<br><span style=\"color:#FF8000\">猛击（被动）</span><br>在攻击中有35% 的几率造成0.01秒的眩晕，+100点的附加伤害。";
tooltips['rnec'] = "<span style=\"color:#FFCC00\">属性：</span><br />增加24点的攻击力<br />提升25%的攻击速度。<br><br><span style=\"color:#FF8000\">连锁闪电（被动）</span><br>在攻击中有25%的概率放出能跳跃4次的连环闪电，造成120点伤害，不衰减 。<br><br><span style=\"color:red\">法球效果不可叠加</span>";
tooltips['wswd'] = "<span style=\"color:#FFCC00\">属性：</span><br />增加22点敏捷<br />增加10点的智力<br><br><span style=\"color:#FF8000\">反馈（被动）</span><br>每次攻击燃烧目标20点魔法,同时造成等量的伤害<br><br><span style=\"color:#FF8000\">净化（主动）</span><br>削除目标身上的魔法效果,将敌方单位的移动速度降低至1/5,持续4(15)秒直接消灭召唤生物.<br><br /><span style=\"color:#99CCFF\">施法距离：</span>600.<br /><span style=\"color:#99CCFF\">冷却时间：</span>12秒.<br><br><span style=\"color:red\">法球效果不可叠加</span><br>购买合成书可升级,最高2级."
tooltips['kybl'] = "<span style=\"color:#FFCC00\">属性：</span><br />增加15点所有属性<br />提升6点/秒的生命回复速度<br>提升150%的魔法回复速度<br><br><span style=\"color:#FF8000\">法术否定（被动）</span><br>每20秒抵挡一次指向性法术攻击。<br /><br /><span style=\"color:#99CCFF\">冷却时间：</span>20秒";
tooltips['schl'] = "<span style=\"color:#FFCC00\">属性：</span><br />增加15%攻击速度<br />提升10点的所有属性<br>增加16点敏捷<br>提升10%的移动速度<br><br><span style=\"color:#FF8000\">幻影（主动）</span><br>制造两个幻影,拥有本体33%的攻击力,承受350%的伤害.<br /><br /><span style=\"color:#99CCFF\">持续时间：</span>20秒<br /><span style=\"color:#99CCFF\">冷却时间：</span>50秒";
tooltips['I029'] = "<span style=\"color:#FFCC00\">属性：</span><br />提升10点的所有属性<br />提高200点生命上限<br>提高150点魔法上限<br><br><span style=\"color:#FF8000\">奥义提升（被动）</span><br>提升某些英雄大招的威力.<br /><br />详解请访问http://DotA.<b style=\"color:red;\">R</b>eplays.<b style=\"color:red;\">N</b>et论坛DotA综合区.";
tooltips['quel'] = "<span style=\"color:#FF8000\">压制（被动）</span><br>远程英雄使用对非英雄单位额外造成12%的伤害.<br />近程英雄使用对非英雄单位额外造成32%的伤害.<br /><span style=\"color:#FF8000\">砍树（主动）</span><br>砍掉一棵树<br /><br><span style=\"color:red\">装备唯一</span><br /><br /><span style=\"color:#99CCFF\">冷却时间：</span>5秒<br><br><span style=\"color:red\">船长不可以使用!</span><br><br>详解请访问http://DotA.<b style=\"color:red;\">R</b>eplays.<b style=\"color:red;\">N</b>et论坛DotA综合区.";
tooltips['poor'] = "<span style=\"color:#FFCC00\">属性：</span><br>增加6点敏捷<br /><br /><span style=\"color:#FF8000\">伤害抵挡（被动）：</span><br>受到普通攻击抵挡20点英雄造成的伤害(远程英雄使用抵挡10点英雄造成的伤害),同时有60%的概率抵挡20点非英雄造成的伤害.<br><br>详解请访问http://DotA.<b style=\"color:red;\">R</b>eplays.<b style=\"color:red;\">N</b>et论坛DotA综合区.";
tooltips['rej4'] = "<span style=\"color:#FFCC00\">属性：</span><br />受到普通攻击时有60%的概率抵挡20点伤害(远程英雄使用抵挡10点伤害)";
tooltips['yzlk'] = "<span style=\"color:#FFCC00\">属性：</span><br />增加6点力量<br />增加50%魔法回复速度<br><br><span style=\"color:#FF8000\">灵魂释放（主动）</span><br>释放一个储存的灵魂，在接下来的8秒内，回复/伤害一个友方/敌方英雄单位400/200点生命,附近1400范围内有敌方英雄死亡时自动充能，受到来自玩家的攻击驱散回复效果。每个英雄死亡只能给1个影之灵龛充能<br><br /><span style=\"color:#99CCFF\">施法距离：</span>950.<br /><span style=\"color:#99CCFF\">冷却时间：</span>10秒.";
tooltips['xlda'] = "<span style=\"color:#FFCC00\">属性：</span><br />增加40点敏捷<br />增加10点力量<br>增加10点智力<br><br><span style=\"color:#FF8000\">以太冲击（主动）</span><br>对一个敌方英雄使用，使用者和目标同时进入虚无状态，持续3秒。目标受到75+2*使用者敏捷的魔法伤害（法 术攻击·魔法伤害），且移动速度降低30%，持续3秒。<br /><br /><span style=\"color:#99CCFF\">注意：</span>与幽魂权杖共用冷却。可以对自己使用（无伤害，不减速）";
tooltips['lhzj'] = "<span style=\"color:#FFCC00\">属性：</span><br />增加+3/秒的生命回复速度<br />增加50%魔法回复速度<br><br><span style=\"color:#FF8000\">牺牲（主动）</span><br>使用者瞬间牺牲150点生命，来为自己提供150点额外魔法，但额外魔法只持续10秒。如果10秒内这15 0的魔法没有用完，10秒后，由牺牲带来的剩余魔法也会被扣除。持续时间内任何魔法需求都会优先从牺牲获得 的额外魔法中取的。<br><br /><span style=\"color:#99CCFF\">冷却时间：</span>30秒<br /><span style=\"color:#99CCFF\">持续时间：</span>10秒.";
tooltips['mfx'] = "<span style=\"color:#FFCC00\">属性：</span><br />+65移动速度<br />+250魔法值<br><br><span style=\"color:#FF8000\">恢复魔法</span><br>（为600范围的友军恢复135点魔法，45秒冷却，25点魔耗）<br><br /><span style=\"color:#99CCFF\">可被拆分</span>";
tooltips['cdzz'] = "<span>毒性攻击效果，3点/秒的持续性伤害，持续3秒。远程英雄使用减速4%，近战英雄使用减速12%。</span>";
tooltips['yqxz'] = "<span style=\"color:#FFCC00\">属性：</span><br />+6点护甲<br />增加50%魔法回复速度<br><br><span style=\"color:#FF8000\">孤注一掷（主动）</span><br>指向敌人施法你和被施法单位同时降低6点护甲，持续7秒。<br><br /><span style=\"color:#99CCFF\">施法距离：</span>800.<br /><span style=\"color:#99CCFF\">冷却时间：</span>7秒.";
tooltips['rnjg'] = "<span style=\"color:#FFCC00\">属性：</span><br />+8所有属性<br />+8攻击力<br />+5%攻击速度 移动速度光环9<br><br><span style=\"color:#FF8000\">战鼓（主动）</span><br>使用时为附近单位提供额外10%攻击速度，移动速度BUFF。<br><br /><span style=\"color:#99CCFF\">持续:</span>6秒<br /><span style=\"color:#99CCFF\">冷却时间：</span>30秒.";
tooltips['gjzw'] = "<span>商店最多存货量:3<br />商店物品刷新时间：10分钟<br />使你和周围850范围内的所有友方玩家控制的单位隐形（大地图和小地图），并提升15%的移动速度，并使之从小地图上消失。如被敌方英雄或者防御塔探知，BUFF消失。如果攻击小兵或者肉山，BUFF消失。Buff持续时间40秒</span>";
/**********DotA.Replays.Net****************/
